### ISSUE TITLE
Question about pointer arithmetic

### ISSUE THREAD

**Issue by Mengyuan410** [LangProc/langproc-2021-cw#27]
Hello Sir! I have some questions regarding pointer arithmetic.
I found that 
1)When a pointer +/- an integer. Then the integer needs to *4;
2)When a pointer - a pointer. Then the results don't need to *4; (I am not sure about pointer + pointer, is pointer+pointer make sense?)
3) When a pointer-pointer+pointer(sequence doesn't matter). Then the pointer-pointer part *4 again.
Is there any rule for the pointer arithmetic. Is it like if odd number of pointers in the expression, then there is a need to *4. If even number of pointers, then don't need to * 4? :fearful:
![image](https://user-images.githubusercontent.com/83700530/159175334-54694d7d-4325-42e6-95d9-70fb33df87b7.png)
![image](https://user-images.githubusercontent.com/83700530/159175562-1b3ab750-1dd3-48db-9124-04c5f9bd00bc.png)

**Comment by ymherklotz** [comment]
Maybe [this section](http://port70.net/~nsz/c/c89/c89-draft.html#3.3.6) in the standard explains the behaviour.  But basically there are special behaviours if you are subtracting two pointers that are accessing the same structure (getting the offset), otherwise you often have it that one of the pointers (the one on the right) is converted to an integer and used as an offset.

Let me know thought if you have more specific questions about the behaviour after reading the section.

> q-p

Pointers into the same structure, therefore from the standard: 

> When two pointers to members of the same array object are subtracted, the difference is divided by the size of a member. 

So we get the subtraction and then divide the result by 4.

> q-p+r

First you do q-p=1, then you add an int to a pointer, so you do 4+r.

> q-p+t-r

First you do q-p=1, then 4+t, which is 2 away from r and is a new pointer, so then ((4+4+r)-r)/4=2

> q-p+1+r

First you do q-p=1, then 1+1=2 as an int. So then you do r+8=...12+8=...20

**Comment by Mengyuan410** [comment]
Thank you!
