### ISSUE TITLE
Questions about certain features in the parser

### ISSUE THREAD

**Issue by Cathy-DYX** [LangProc/langproc-2021-cw#28]
Hello, there are some features in the parser that I am not sure what they mean.

In the direct declarator, I am not sure what the second and the third line in the above picture means.
![image](https://user-images.githubusercontent.com/62194910/159171409-27d41fe8-4dd5-4380-83f1-90076527cd27.png)
<br />
 
Do we need to implement expressions separated by comma?
![image](https://user-images.githubusercontent.com/62194910/159171447-a5c44af1-1662-4f56-8b0d-4062dca3412f.png)
<br />

For this one, I don't really understand how struct can exist without an identifier name. Should we just ignore this case?
![image](https://user-images.githubusercontent.com/62194910/159173298-7a5e2d7a-82c9-4923-ab9d-9a0d3de0fda1.png)
<br />

Do we need to implement pointer to pointer
![image](https://user-images.githubusercontent.com/62194910/159173319-d58d648a-d17c-40a4-8a41-8247667cc940.png)
<br />

For labelled statement, I am not really sure what how first line is used.
![image](https://user-images.githubusercontent.com/62194910/159175486-cf8739b6-425e-4206-ac23-4e965af6aebb.png)

Thank you so much!!!

**Comment by ymherklotz** [comment]
1. It's hard for me to guess from the grammar as there are many grammars out there, so it would be more useful to point to the official specification.  For example for this point, there is a [section on direct declarators](http://port70.net/~nsz/c/c89/c89-draft.html#direct-declarator) and it then even goes over examples for all the cases, so in this case you are asking about [function declarators](http://port70.net/~nsz/c/c89/c89-draft.html#3.5.4.3) I think.  So the grammar is used to parse function declarations, including the function arguments.
2. No, it's in the list of features that will definitely not be tested.
3. That's how C handled structs originally, you can try it yourself in a C compiler.

```c
int main() {
    struct {int a; int b; } c = {1, 2};
    return c.a;
}
```

The only way to give the struct a name was to use a typedef:

```c
typedef struct {int a; int b; } S;
int main() {
    S c = {1, 2};
    return c.a;
}
```
4. I think that's something that could be tested.
5. Also something that is just part of C.

```c
int main() {
    int x = 0;
    L1: x++;
    if (x < 5) goto L1;
    return x;
}
```

But because `goto` doesn't have to be supported, you might not need to support Labels, but they could just be parsed and ignored as well.

If you have any other questions like 3 and 5, then it might be useful to just try it out with a compiler yourself to see if it accepts it and what it does.

**Comment by Cathy-DYX** [comment]
Thank you!!!
