### ISSUE TITLE
Compiling tests

### ISSUE THREAD

**Issue by Aeroking21** [LangProc/langproc-2021-cw#34]
Hi,

When compiling some of our tests which work, they seem to provide the following warining ` Warning: no .cprestore pseudo-op used in PIC code`. I am not sure of how to remove this warning?

**Comment by ymherklotz** [comment]
This is to restore the value of the global pointer if your function edits it.  For example, if you are accessing values using the global offset table, the offset first needs to be computed (using `.cpload`), and then needs to be reset before returning using `.cprestore`.

So if you are not changing `$gp` directly or through `.cpload`, I don't think you need to worry about that warning.

[More info about `.cprestore` here](https://www.linux-mips.org/wiki/PIC_code).  Also an answer in #30.

**Comment by Aeroking21** [comment]
thanks, when compiling our parser I seem to be getting a lot of warnings such as these and I'm not sure how to remove them? :

```
src/parser.y:150.7-10: warning: type clash on default action: <type> != <> [-Wother]
  150 |     : VOID
      |       ^~~~
src/parser.y:151.7-10: warning: type clash on default action: <type> != <> [-Wother]
  151 |     | CHAR
      |       ^~~~
```

**Comment by ymherklotz** [comment]
I think it's because you didn't provide an action for the rule using braces `{}`.  So instead bison reads it as `{ $$ = $1; }`, which is the default action, and it therefore warns because likely the type of VOID is `<>`, whereas the type of the rule is `<type>` maybe.

more info: https://lists.gnu.org/archive/html/help-bison/2000-10/msg00056.html
