### ISSUE TITLE
Question about nop after lw instruction

### ISSUE THREAD

**Issue by Mengyuan410** [LangProc/langproc-2021-cw#8]
Hello Sir! May I ask something about nop after the lw instruction? I understand that nop is after lw instruction for the purpose of pipelining. But we found that the qemu-mips can return the correct value even **without** nop after lw instruction. Also, it seems that sometimes there are 2 nop and sometimes there is one (shown in the picture below). I am a bit confused about the nop instruction. Do we really need this?

![image](https://user-images.githubusercontent.com/83700530/156903120-bffce440-4896-4195-bf5a-03ecb229b28a.png)

<img src= "https://user-images.githubusercontent.com/83700530/156903111-87ce294a-102a-4fdf-845a-0d51a0c1b282.png" width = "350">

**Comment by ymherklotz** [comment]
So for jumps you definitely need a branch delay slot.  However, for loads it seems like there isn't, and looking at documentation, only the first MIPS CPUs seemed to expose the load delay slot.  So I don't think these nops are technically necessary, and GCC will probably remove them if you compile with optimisations.  Especially for emulation with `qemu`, I guess it will never have the delay slot, but there is always a possibility that it might actually happen in the hardware itself, which is why I think gcc is being safe and adding it.

For the `mflo` instruction, the standard says that one should not use a load instruction within two instructions of a `mflo` or `mfhi`, so that's why gcc added two nops there.
